# Generated by Django 3.1.1 on 2020-10-07 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.lesson'),
        ),
    ]
